baseURL = "/"
languageCode = "en-us"
title = "Aashray's Blog"
theme = "m10c"
github = "https://github.com/AashrayAnand"
email = "aaanan@microsoft.com"

[params]
    author = "Aashray Anand"
    description = "Software engineer, writing about what I do in my free time"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/AashrayAnand/"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/anand_aashray"

  # Red theme
  [params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    lightColor = "#d6d6d6"
    lightestColor = "#d3d3d3"
    primaryColor = "#ffffff"