baseURL = "/"
languageCode = "en-us"
title = "Aashray's Blog"
theme = "m10c"
github = "https://github.com/AashrayAnand"
email = "aaanan@microsoft.com"

[params]
    author = "Aashray Anand"
    description = "Software engineer, writing about what I do in my free time"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/AashrayAnand/"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/anand_aashray"
	
  #Default theme
  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#57cc8a"
